### PR TITLE
new tool Lasercutter Techdraw Export

### PR DESCRIPTION
**Pull request by chbergmann**
Hi, I have integrated a new tool into your workbench derived from the macro Lasercutter SVG Export Macro

### CODE REVIEW

**Comment by luzpaz** [comment]
@execuc please respond

**Comment by execuc** [comment]
Hello, I apologize for the late reply and I thank you very much for your evolution. 
I will merge it as soon as I can because I am very busy at work at the end of the year.

**Comment by ifohancroft** [comment]
Just wanted to check the status on this as I badly need something that can take a 3D object I made and flatten it so I can send it for cutting.

**Comment by luzpaz** [comment]
we seriously can't let this code rot.

**Comment by chbergmann** [comment]
I decided to move the tool to the Curved Shapes Workbench

**Comment by nelsonic** [comment]
https://github.com/chbergmann/CurvedShapesWorkbench ⭐

**Pull request closed without merging**
